### ISSUE TITLE
Error: post type from endpoints "posts,pages,media" with slug "service-worker.js" not found

### ISSUE THREAD

**Issue by i-bsd** [chakra-ui/frontity-chakra-ui-theme#6]
Love the theme but it's not working correctly.

The front page loads fine and posts are pulled but if I try to view a post, I get this dump (+ white page in browser preview):

```
Because you write your CSS inside a JavaScript string you actually have to do double escaping, so for example "content: '\00d7';" should become "content: '\\00d7';".
You can read more about this here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#ES2018_revision_of_illegal_escape_sequences
Error: post type from endpoints "posts,pages,media" with slug "service-worker.js" not found
    at Object.eval (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/postType.ts:8:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
You have illegal escape sequence in your template literal, most likely
inside content's property value.
Because you write your CSS inside a JavaScript string you actually have to do double escaping, so for example "content: '\00d7';" should become "content: '\\00d7';".
You can read more about this here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#ES2018_revision_of_illegal_escape_sequences
Error: post type from endpoints "posts,pages,media" with slug "service-worker.js" not found
    at Object.eval (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/postType.ts:8:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
You have illegal escape sequence in your template literal, most likely
inside content's property value.
Because you write your CSS inside a JavaScript string you actually have to do double escaping, so for example "content: '\00d7';" should become "content: '\\00d7';".
You can read more about this here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#ES2018_revision_of_illegal_escape_sequences
```

I assume this is the problem but don't know how to fix it:

> Error: post type from endpoints "posts,pages,media" with slug "service-worker.js" not found

**Comment by i-bsd** [comment]
Oddly it seems to work better with the test.frontity.io API but not any other WP site of ours.

Any idea why?

**Comment by i-bsd** [comment]
Nevermind. Turns out Wordfence was the culprit blocking API access.

Thanks for your awesome work!

**Comment by luisherranz** [comment]
This one was solved here: https://github.com/frontity/frontity/pull/344
